### ISSUE TITLE
block.break event has event.player === event.getEntity(), block.place doesn't

### ISSUE THREAD

**Issue by Lupus590** [KubeJS-Mods/KubeJS#106]
I would expect consistency.

**Comment by MaxNeedsSnacks** [comment]
A BlockPlaceEventJS doesn't actually have a player attribute as you can see here

https://github.com/KubeJS-Mods/KubeJS/blob/99c7cd7aef519664446a85c76a9c01d5c17c13bd/common/src/main/java/dev/latvian/kubejs/block/BlockPlaceEventJS.java#L17-L21

This is just due to the original Forge / Fabric event's structure, which may accept non-player entities, as well. That said, this obviously makes event.player return `undefined`, so if you want to compare the entity to something, you should probably just use their UUIDs:

https://github.com/KubeJS-Mods/KubeJS/blob/99c7cd7aef519664446a85c76a9c01d5c17c13bd/common/src/main/java/dev/latvian/kubejs/entity/EntityJS.java#L67-L69

In the future, there *might* be ways to "convert" an EntityJS to a PlayerJS, though our long term goal is actually to mostly do away with wrapper classes entirely and just integrate our functionality into the relevant vanilla classes
