### ISSUE TITLE
Question more mekanism recipes in Mekanism integration

### ISSUE THREAD

**Issue by edotenseilove** [KubeJS-Mods/KubeJS#111]
Great mod will there be more recipes supported like crystallizing and more and can i find an updated list of all recipe types supported somewhere?

Thank you editing recipes thanks to this mod is so easy. Much better then using datapacks

**Comment by choukpop** [comment]
i want to create a new custom recipe to use Energized Smelter
how to do that?

**Comment by hotdog95** [comment]
From my understanding of how this works, the problem here is that it's entrily limited to mekanism capabilities.

I could be wrong

If you can can in fact make an Energized Smelter recipe as a JSON, then yes you can do that, but that comes down to mekanism implementing a recipe type "energized smelter" for their recipe JSON's 
. At current (while I have not looked into it) I believe the energized smelter only accepts furnace recipes (not even blast furnace recipes)

**Comment by MaxNeedsSnacks** [comment]
Actually yeah, you can add additional smelting recipes to the Energised Smelter. To do that, use this recipe type:

https://github.com/mekanism/Mekanism/wiki/Recipe-Type-JSON-Syntax#smelting

**Comment by hotdog95** [comment]
oh cool! I like being proven wrong :)

**Comment by choukpop** [comment]
> Actually yeah, you can add additional smelting recipes to the Energised Smelter. To do that, use this recipe type:
> 
> https://github.com/mekanism/Mekanism/wiki/Recipe-Type-JSON-Syntax#smelting
> 
> I'm not entirely certain whether KubeJS-Mekanism has integration for this, but when in doubt, you can always just use `event.custom` with the actual JSON syntax

so how i made that on code?
