### ISSUE TITLE
[Question] Can you stop an item from being consumed in a recipe?

### ISSUE THREAD

**Issue by GreatestFool** [KubeJS-Mods/KubeJS#134]
Say I have a bucket full of lava, the lava I'd want to use and the bucket I'd like to keep. From what I remember vaguely, you could call a transform on CraftTweaker to simply change it to the normal bucket or something, in effect, 'using' the lava bucket and keeping an empty one.

Is there a function(or whatever those are actually called) for _not_ consuming an item used in a recipe?

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #55

**Comment by MaxNeedsSnacks** [comment]
For reference, this is being worked on, but only sporadically unfortunately as neither of us have the time currently ^^

**Comment by FirewallDaProtogen** [comment]
hey sorry to comment on an old issue, but both are marked as complete however im having the same question of how?
because as far as i know, this is not mentioned in the wiki anywhere, (tried searching for consume, remain / remaining, and bucket)
so ideally some clarification on how to do this and also a wiki entry would be amazing. thanks!
