### ISSUE TITLE
[2 requests] world generation customizer and elementalcraft support addon

### ISSUE THREAD

**Issue by DerShendi** [KubeJS-Mods/KubeJS#143]
Ive been tryin to look for a way to make it so that only specific biomes spawn in the world but couldnt find any and datapacks dont seem to like the mods im using(ffs all im trying is to make it so that only ocean biomes spawn). 
And as for the elemental addon its self explainatory it would be nice to have a way to create your own ritual recipes

**Comment by pm065** [comment]
> And as for the elemental addon its self explainatory it would be nice to have a way to create your own ritual recipes

You can use event.custom for recipes with no integration. You could even shove it in a reusable function to make a kind of compatibility yourself for only that modpack.

**Comment by MaxNeedsSnacks** [comment]
1. As pm said, until we (or the dev, or a third party) can find the time to make a plugin for ElementalCraft, use event.custom with the same json structure you're used to
2. I'm pretty sure Biome spawning is done in the dimension JSON (so `data/minecraft/dimension/overworld.json` for example), you'd have to fiddle with the chunk generator's biome source, which I'm not entirely sure how to do that with JSONs myself, but there's *hopefully* some online guides on it. Since KubeJS can provide JSONs like a normal datapack through `kubejs/data`, this shouldn't be much of a problem ^^
