### ISSUE TITLE
KubeJS causing registry synchronization issues when attempting to join a server

### ISSUE THREAD

**Issue by camckenn** [KubeJS-Mods/KubeJS#204]
Hello,

I am currently experiencing an issue that appears to be caused by KubeJS based on my examination of my debug file.  I am using CurseForge as my client and All the Mods 6 as the overall modpack (with Optifine as an addition, but it should not cause this bug).  Single player worlds can be created, although they have some issues loading when I try to re-enter them after quitting (not sure this is an issue with KubeJS, though).  However, as soon as I try to join my friends' server, I get "failed to synchronize registry data from server."  Upon checking the debug file, I found that the issues with the registry were all related to KubeJS-specific objects.  What can I or the server owner do to resolve this issue?  The server owner sent me the exact modpack he was using (it had Optifine in it, which is why it's present on my own system) in a zip file, and I have also tried deleting and reinstalling the KubeJS files in it specifically.  

I will attach the debug file.  As you'll see, assuming "immersiveengineering" is related to KubeJS, KubeJS does encounter texture resolution errors in startup.  Toward the end of the file is where you'll find my attempt to connect to the server and the "unidentified mappings."

Thanks!

If in the event that this problem is not actually caused by KubeJS and you cannot help, please let me know and I'll take my question to a different forum.

[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/7356200/latest.log)

**Comment by Spiker985** [comment]
@camckenn From your log, it appeared the server was possible loaded as a vanilla server, and not as a modded server due to this line: 
`[15Oct2021 17:39:23.434] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [jeresources, advancementplaques, kubejs_create, pickletweaks, integratedtunnelscompat, appleskin, lootr, allthetweaks, aquaculture, byg, kubejs_immersive_engineering, cosmeticarmorreworked, xpbook, rsrequestify, cyclopscore, astralsorcery, advancedperipherals, aiotbotania, tinyredstone, eidolon, managear, kubejs_mekanism, incontrol, findme, rsgauges, envirotech, glassential, terraforged, configurableextramobdrops, cookingforblockheads, citadel, dankstorage, mightyarchitect, moreminecarts, potionsmaster, culinaryconstruct, bookshelf, cartographer, sophisticatedbackpacks, projectred-illumination, buildinggadgets, lightingwand, mcwdoors, kubejs_blood_magic, mekanismgenerators, xnetgases, absentbydesign, dummmmmmy, mob_grinding_utils, twilightforest, rsinfinitybooster, equipmentcompare, chipped, chocolate, mcwbridges, resourcefulbees, usefulbackpacks, commoncapabilities, endertanks, entangled, compressium, mekanismadditions, lollipop, valkyrielib, mcwfences, simplylight, tgcropesmod, atmadditions, pamhc2foodextended, solarflux, dpanvil, patchouli, rftoolsstorage, collective, rftoolscontrol, projectred-transmission, drawerstooltip, integratedtunnels, thermal_expansion, elevatorid, lostcities, mysticalcustomization, ftbultimine, gunpowderlib, betterstrongholds, buildersaddition, starterkit, mekanismtools, architectury, computercraft, compactcrafting, trashcans, tramplestopper, bwncr, smallships, observable, cyclic, rhino, biggerreactors, cucumber, trashslot, pamhc2trees, flatbedrock, craftingstation, itemfilters, elementalcraft, platforms, metalbarrels, abnormals_core, ae2extras, create, ensorcellation, waystones, zycraft, clumps, enviromats, appliedenergistics2, comforts, artifacts, cb_multipart_minecraft, framedcompactdrawers, dimstorage, dungeoncrawl, demagnetize, restrictions, lazydfu, travel_anchors, mcjtylib, explorerscompass, mahoutsukai, integrateddynamicscompat, mininggadgets, akashictome, ftbchunks, bloodmagic, scuba_gear, brandonscore, immersiveposts, mysticalagriculture, selene, tconstruct, rftoolsutility, enchdesc, titanium, toolbelt, mana-and-artifice, silentlib, exchangers, ctiers, forbidden_arcanus, archers_paradox, omgourd, enviroenergy, quark, creativewirelesstransmitter, fastbench, fluxnetworks, storagedrawers, enderchests, minecolonies, pylons, chisel, engineersdecor, solcarrot, modularrouters, refinedstorageaddons, botanicalmachinery, expandability, valhelsia_core, morphtool, translocators, balancedenchanting, createaddition]`

Seeing as how this issue was created nearly two months ago, I'm going to close this issue as a wontfix since it seems to be external to the mod itself.
