### ISSUE TITLE
[Bug]: Server Scripts Not Loading

### ISSUE THREAD

**Issue by GW-Dev** [KubeJS-Mods/KubeJS#278]
When I log into a world created with an old version of KubeJS, I get the error 'Failed to read script pack server_scripts: : java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/level/world/LevelJS'.

Full KubeJS Sever Log: [link](https://pastebin.com/pfK0yMkG)

1.18.1 Forge
Error with  https://www.curseforge.com/minecraft/mc-mods/kubejs-forge/files/3627134

**Comment by cannon9009** [comment]
This happens with worlds created with the latest version as well. I made a world a few hours ago and it outputted the same error in the server logs. Log is here: [link](https://pastebin.com/T9Y0jYpH)

This error's appearance also seems to correlate with an unfortunate other issue: Recipes in the game never appear in the crafting table/players "book" (the button with the green book on it), and things like R.E.I aren't able to display recipes either.

This may or may not be related to the LevelJS issue, since looking in the server log suggests that the mod literally finishes recipe modifications in the microseconds, something that should genuinely be impossible under most, if not all, modding circumstances...

**Comment by MaxNeedsSnacks** [comment]
Please update all of the following mods:

- FTB Chunks
- FTB Quests
- KubeJS Immersive Engineering

There have been breaking changes pushed to Kube that required updates on the end of these mods' KubeJS addons (as well as maybe some other mods out there, these are just the ones I fixed)
