### ISSUE TITLE
on click 1.19

### ISSUE THREAD

**Issue by Joshernoob** [KubeJS-Mods/KubeJS#384]
### Minecraft Version

1.19

### KubeJS Version

kubejs-forge-1900.5.5-build.12

### Rhino Version

rhino-forge-1802.1.14-build.182

### Architectury Version

architectury-5.7.27-forge

### Forge/Fabric Version

Forge- 41.0.38

### Describe your issue

Game loads in just fine but as soon as i click anything in the main menu it give on click error

(this is from mod crashy so if link doesnt work i can make a new one on a diffrent site) https://bytebin.lucko.me/Tq8FagY5V
![Screenshot 2022-06-18 141638](https://user-images.githubusercontent.com/64944433/174451445-ee91de81-50bb-4d10-a9f2-dbbfdbf4930e.png)

added the picture incase that make things faster

**Comment by MaxNeedsSnacks** [comment]
Are you using Building Gadgets? If so, that mod seems to be causing issues with KubeJS right now, for whatever reason...

**Comment by Joshernoob** [comment]
yes i currrently am

**Comment by MaxNeedsSnacks** [comment]
Can you try removing it and see whether things work then? I'm still looking into why this is happening, but it's... likely to be on BG's end

**Comment by Joshernoob** [comment]
i removed it and charging gardgets just to make sure and still getting an on click erro
![Screenshot 2022-06-18 142412](https://user-images.githubusercontent.com/64944433/174451646-342656b9-3b68-4dc3-8ac8-f11fcf098fdc.png)

**Comment by MaxNeedsSnacks** [comment]
Can you send us the crash report of that once again

**Comment by Joshernoob** [comment]
new crash report
![Screenshot 2022-06-18 143302](https://user-images.githubusercontent.com/64944433/174451906-8f5f6800-52dd-418b-8ac3-7224bc3bc31a.png)

**Comment by MaxNeedsSnacks** [comment]
Can you please enable debug.log and try again and then send us that, and also please if you can post your logs to an actual paste site instead of putting a screenshot here.

(If you're on CurseForge, you can enable the debug.log by going to the game-specific settings for Minecraft and toggling this switch)
![image](https://user-images.githubusercontent.com/12750501/174487999-bbe2f795-23a9-4b79-b439-de1601d97d18.png)

**Comment by Joshernoob** [comment]
(Debug was slit do to size limit on site)
Debug.log part 1:https://pastebin.com/6Sh56Ja7
Debug.log part 2: https://pastebin.com/sqs2FTDv
Debug.log part 3: https://pastebin.com/h0iSTWJx
Debug.log part 4: https://pastebin.com/eGpCbWwN

Latest.log: https://pastebin.com/guZr0TDU

**Comment by MaxNeedsSnacks** [comment]
Extreme Reactors is forcing Forge to roll back to the Vanilla registry game state because of code relying on their old fluid API. KubeJS is being blamed here because it's the first mod to "expect" a registry object to be present whenever you load into the world (given that it hooks into when datapacks load and tries to get a serialiser we have for custom shaped recipes)

Apparently this is a known issue with Forge in 1.19, see https://github.com/MinecraftForge/MinecraftForge/issues/8720
