### ISSUE TITLE
Related to BotanyPots/adding sapling stop working after KubeJS 1604.3.1.84

### ISSUE THREAD

**Issue by TheNeurotox** [KubeJS-Mods/KubeJS#39]
When I use this script (it's adding tree in botany pots), when a sapling is used in hopper botany pots, the tree grows but they stop at 100% and nothing append.
With KubeJS 1604.3.1.84 and before, the tree grow then it get harvest like any other crops.

I have try many version of many mods involve (BotanyPots, rhino, architectury, kubejs) and it's when I pass at KubeJS over 1604.3.1.84 that the issue occur.  I'm not sure what to look at this point.

Mods list of my last test:
-Bookshelf-1.16.4-9.1.13.jar
-Botania-1.16.3-409.jar
-BotanyPots-1.16.4-6.0.7.jar
-Cucumber-1.16.4-4.1.5.jar
-MysticalAgradditions-1.16.4-4.1.2.jar
-MysticalAgriculture-1.16.4-4.1.3.jar
-MysticalCustomization-1.16.4-2.1.1.jar
-Patchouli-1.16.2-47.jar
-architectury-1.1.54-forge.jar
-curios-forge-1.16.4-4.0.3.0.jar
-jei-1.16.4-7.6.0.58.jar
-kubejs-1604.3.1.104-forge.jar
-rhino-1.7.13.9.jar

[botany_pots.js.txt](https://github.com/KubeJS-Mods/KubeJS/files/5610574/botany_pots.js.txt)

ref: https://github.com/AllTheMods/ATM-6/issues/379

**Comment by andrewsf** [comment]
The latest Rhino plugin is using Rhino 1.7.13, which is pretty much the bleeding edge on that project, but [even the latest Rhino is pretty poor on ES2015 support](https://mozilla.github.io/rhino/compat/engines.html#ES2015).

FWIW, [GraalVM's doing great](https://github.com/graalvm/graaljs/blob/master/README.md#current-status) with full ES2020 support.

**Comment by LatvianModder** [comment]
Not that I didn't look at Graal before switching. I spent a lot of time with both engines. Graal had more problems with KubeJS specifically than Rhino. If I was gonna break all scripts and design a new syntax, then sure, Graal would be the better option, but Rhino adds many good ES6 features (arrow functions, working array functions, regex, for..in, for..of etc) and only breaks couple scripts while being 10x smaller. You have to think about pack updates too. And Rhino being way smaller its also easier to work with in my own fork. I added template strings recently for example. So that's my official reason for using Rhino over Graal

**Comment by TheNeurotox** [comment]
Thanks for the fix !
