### ISSUE TITLE
[1.16.4 forge, v 1604.3.2.121] Mekanism Addon doesn't work for Infusing

### ISSUE THREAD

**Issue by theLadyStardust** [KubeJS-Mods/KubeJS#43]
The example that was on the Curseforge page for the Mekanism addon for the Metallurgic Infuser doesn't seem to be working. Is the example incorrect? Otherwise, Kube and the mekanism addon seems to be working, the recipe I added with the crusher works fine. Here's the line I'm using, it's in `events.listen` for `recipes`, and other recipes in the same block are working.  
`event.recipes.mekanism.metallurgic_infusing('minecraft:comparator', 'minecraft:nether_quartz', 'mekanism:redstone', 20)`
I've tried using `item.of()` on the inputs/outputs, no dice. Any help would be greatly appreciated. A few other questions that the docs weren't able to answer - Is there a way to add new fluids the same way you can add items and blocks? and is there a way, aside from making multiple recipes, to allow for multiple inputs, aside from forge tags? Aside from this, the mod's been working really well for what I want it to do, thanks for making it!

**Comment by MaxNeedsSnacks** [comment]
Can you provide a full script file please? (go to https://hastebin.com/ and paste the contents there, then send the link here)

Also please tell me which folder the script is in, is it in `kubejs/server_scripts` or another folder?

**Comment by theLadyStardust** [comment]
It's in `server_scripts`. I managed to get the infusing recipe to work, it was likely something else in the file. I did have an issue with injecting recipes, however. Here's the file, the lines that aren't working are at 438 - 440. https://hastebin.com/kiqefixiju.csharp

**Comment by MaxNeedsSnacks** [comment]
Your gas ingredient is formatted incorrectly:
`{gas: "mekanism:sulfuric_acid", 200}`
needs the amount key because you're using a js object, so:
`{gas: "mekanism:sulfuric_acid", amount: 200}`

As for your other questions:

> Is there a way to add new fluids the same way you can add items and blocks?
Yes, there is an event called `fluid.registry` which you can use to create fluids with using a [Fluid Builder](https://github.com/KubeJS-Mods/KubeJS/blob/fcb071661bd59a70ce6a7a886f02431bdc3ade11/common/src/main/java/dev/latvian/kubejs/fluid/FluidBuilder.java)

> and is there a way, aside from making multiple recipes, to allow for multiple inputs, aside from forge tags?
Yes, vanilla ingredients support lists of tags / items and you can achieve the same effect in KubeJS by using `ingredient.of([...])`

Hope I could help!

**Comment by theLadyStardust** [comment]
That's perfect! Thanks so much!
