### ISSUE TITLE
Add the ability for any entity to have the `Marker` attribute

### ISSUE THREAD

**Issue by Ethiarpus** [KubeJS-Mods/KubeJS#439]
### Describe the feature

Armor Stands have a property called `Marker` which renders them intangible, removing their hitbox and causing all interactions/clicks to pass directly through them to the blocks or entities behind them. It would be useful for scripters to be able to programmatically apply this property to any entity (including players) with a new `mutable boolean marker` property of EntityJS

**Comment by ChiefArug** [comment]
This is unlikely to happen because most of the wrapper classes are getting removed in KubeJS 6, so improving them isnt a high priority.

And as for applying it to any entity, I think that is outside the scope of KubeJS. Mostly because I believe marker armour stands dont ever actually get sent to the client, they only exist on the server side, meaning some mods assumptions about entities existing both sides could be broken, and (based on my uninformed guess) it would require considerable modifications to MCs code to get working.

**Comment by Ethiarpus** [comment]
Luckily markers *do* get sent to the client! Invisible ones can be seen in spectator mode, and markers without the `Invisible` tag get sent and are fully visible to normal players, but have a 0x0x0 hitbox

**Comment by ChiefArug** [comment]
According to [the snapshot page](https://www.minecraft.net/en-us/article/minecraft-snapshot-21w15a#:~:text=Only%20exist%20on%20the%20server%20side,%20are%20never%20sent%20to%20clients) they are not sent to clients.
Or are armour stands with the marker tag a completely different thing and Mojank just implemented the same thing twice?

**Comment by Ethiarpus** [comment]
Yes, they saw the widespread use of Marker armor stands and added a new more efficient entity to handle it. Essentially yes, they implemented the same thing twice, but marker armor stands are visible
![image](https://user-images.githubusercontent.com/33235902/182001971-819b1f0f-f40a-4096-a3f4-8c36716f9f8c.png)

**Comment by ChiefArug** [comment]
I am going to close this as not planned, because its quite a big feature that I dont think many people would have a use for, and outside the scope of KubeJS, not to mention possible hell for mod compatibility.
I could definitely see another mod doing this through something like an nbt tag though.

As a jerry-rigged workaround you could kill the entity and store its data on an marker armour stand/marker entity, then re-summon it when needed, or give it levitation and no ai and 'store' it at some extreme value (like y: 2,000,000)
