### ISSUE TITLE
all liquids have the same texture

### ISSUE THREAD

**Issue by IETTCQV** [KubeJS-Mods/KubeJS#452]
### Minecraft Version

1.16.5

### KubeJS Version

1605.3.18-build.129

### Rhino Version

1605.1.4-build.63

### Architectury Version

1.23.33

### Forge/Fabric Version

Forge 36.2.35

### Describe your issue

OptiFine-1.16.5_HD_U_G8_pre2 and older versions.

all liquids have the same texture when optifine is connected
![одинаковые текстуры](https://user-images.githubusercontent.com/72767917/184669447-b3e95375-5fd7-4222-89bc-b85c2c1bdd47.png)
.

**Comment by Spiker985** [comment]
Due to the way that Optifine works, we do not support installations with it installed.

However, there are alternatives:
Performance: [Useful mods - Performance](https://github.com/NordicGamerFE/usefulmods/tree/main/Performance)
Dynamic Lighting: [Lucent](https://www.curseforge.com/minecraft/mc-mods/lucent)
Zoom: [Ez Zoom](https://www.curseforge.com/minecraft/mc-mods/ezzoom)
Shaders - [Vanilla based Fabulous graphics shaders (Resource Pack)](https://github.com/bradleyq/mc_vanilla_shaders/releases/tag/v2.3) or [Oculus (works with existing shaders)](https://www.curseforge.com/minecraft/mc-mods/oculus)
