### ISSUE TITLE
stom shaped and shapeless recipe types for advanced features

### ISSUE THREAD

**Issue by LatvianModder** [KubeJS-Mods/KubeJS#55]
To support:

- Damaging ingredients
- Transforming/remaining ingredients (bucket style)
- Changing NBT/damage with a function
- Disable mirroring

**Comment by Spiker985** [comment]
With the new shaped and shapeless recipe types (6c10f799146f3a7261fa81cf8c7d50dc14641131), and ingredient actions (6c10f799146f3a7261fa81cf8c7d50dc14641131) are items 1, 2, and 4 marked complete?

Or is 3 also complete due to the ability to technically merge NBT by using the `.withNBT()` method in ItemStackJS
