### ISSUE TITLE
ServerEvents.recipes() crashes the game [modded]

### ISSUE THREAD

**Issue by NatiM6** [KubeJS-Mods/KubeJS#651]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.1-build.300.jar

### Rhino Version

1902.2.2-build.268.jar

### Architectury Version

6.5.85

### Forge/Fabric Version

Forge 43.2.21

### Describe your issue

Minecraft crashes when ServerEvents.recipes() is a part of the server script.
This happens even when the callback function is empty, like `event => {}`.

ServerEvents.tags() works fine.

### Crash report/logs

https://pastebin.com/SHYMyxVc

**Comment by NatiM6** [comment]
There's a lot of mods there though, I have to check which one is not compatible.

**Comment by MaxNeedsSnacks** [comment]
Ho boy, okay... so the issue here I think is that... there is a json file that's just `null`, and the map is __supposed__ to be filled with JsonObjects (this is true in vanilla as well, so this would also error in vanilla), but that said... these recipes should normally just be skipped in case of an error, so it does warrant fixing
