### ISSUE TITLE
Falling back to vanilla: ItemStack 'result' can't be empty!

### ISSUE THREAD

**Issue by BazZziliuS** [KubeJS-Mods/KubeJS#809]
### Minecraft Version

1.20.1

### KubeJS Version

kubejs-forge-2001.6.5-build.2

### Rhino Version

rhino-forge-2001.2.2-build.18

### Architectury Version

architectury-9.2.14-forge

### Forge/Fabric Version

Forge 47.2.20

### Describe your issue

I noticed an error and decided to report it
If you need anything from me, let me know

### Crash report/logs

https://paste.fuix.net/AabtheQ

**Comment by ChiefArug** [comment]
Can you show all your recipe scripts please? Specifically any that have json (event.custom) recipes.

**Comment by BazZziliuS** [comment]
The fact is that in kubejs I do not have recipes related to "mekaweapons"

Can I send you a zip here?

**Comment by ChiefArug** [comment]
I don't think the mekaweapons warning is related, its probably just the mod author forgetting something in their recipe class. Yes you can send a zip of the code here.

**Comment by BazZziliuS** [comment]
[server_scripts.zip](https://github.com/KubeJS-Mods/KubeJS/files/14625820/server_scripts.zip)

**Comment by ChiefArug** [comment]
A paste version of the scripts is available here: https://gnomebot.dev/paste/1218734924660604998

**Comment by ChiefArug** [comment]
Looks like it is caused by one of your remove lines, though I'm not sure which (its likely that it would be all of them too).
Specifically its caused by filtering a json recipe by output and the code in KJS here: https://github.com/KubeJS-Mods/KubeJS/blob/2001/common/src/main/java/dev/latvian/mods/kubejs/recipe/JsonRecipeJS.java#L40 where KubeJS just casts JsonRecipeJS to Recipe, which I don't think would ever work.

As a temporary fix you can disable match json recipes in the kubejs/config/common.properties file.

**Comment by ChiefArug** [comment]
I believe this was been fixed a while ago.
