### ISSUE TITLE
Is there a way to remove smelting/blasting/smoking recipes?

### ISSUE THREAD

**Issue by Fireztonez** [KubeJS-Mods/KubeJS#95]
Hello,
I currently work on a modpack for Minecraft 1.16.5, and I start changings somes recipes with KubeJS. For crafting recipes, there have a lot of  possibility on the documentation, this is really great! But I can't find way on the documentation right now, to remove Furnace, Blasting or smoking recipes. Is it currently possible to remove thoses recipes by input or output for each of those machine?

**KubeJS Version:** 1605.3.6-build.175
**Rhino Version:** 1.7.13-build.14
**Architectury API Version:** 1.8.131
**Minecraft Version:** 1.16.5
**Forge Version:** 36.0.54

**Comment by pjlasl** [comment]
I had a similar question for my modpack because a mod used wood planks in the stonecutter. here are all the remove commands

I pass the input and type to make sure I don't kill all stonecutter recipes :)

---From their wiki...

event.remove({}) // Deletes all recipes
  event.remove({id: 'minecraft:glowstone'}) // Removes data/minecraft/recipes/glowstone.json
  event.remove({input: '#forge:dusts/redstone'}) // Removes all recipes where input is Redstone Dust tag
  event.remove({output: '#minecraft:wool'}) // Removes all recipes where output is Wool tag
  event.remove({mod: 'quartzchests'}) // Remove all recipes from Quartz Chests mod
  event.remove({type: 'minecraft:campfire_cooking'}) // Remove all campfire cooking recipes
  event.remove({output: 'minecraft:cooked_chicken', type: 'minecraft:campfire_cooking'}) // You can combine filters, to create ANDk logic

**Comment by MaxNeedsSnacks** [comment]
See pjlasl's answer, it's possible to filter what kinds of recipes you want to remove

**Comment by red2blue** [comment]
What about a custom grinder?

simplegrinder:grinder/iron_ore_to_raw_iron
